Repository Andrewwango/govuk-accessible-search, pull requests merged in 2023-05, with the labels that each got.

#10 Setup nodejs project
  README.md
  component/DELETE_tsconfig.json
  component/assets/fonts/bold-affa96571d-v2.woff
  component/assets/fonts/bold-b542beb274-v2.woff2
  component/assets/fonts/light-94a07e06a1-v2.woff2
  component/assets/fonts/light-f591b13f7d-v2.woff
  component/assets/images/favicon.ico
  component/assets/images/govuk-apple-touch-icon-152x152.png
  component/assets/images/govuk-apple-touch-icon-167x167.png
  component/assets/images/govuk-apple-touch-icon-180x180.png
  component/assets/images/govuk-apple-touch-icon.png
  component/assets/images/govuk-crest-2x.png
  component/assets/images/govuk-crest.png
  component/assets/images/govuk-logotype-crown.png
  component/assets/images/govuk-mask-icon.svg
  component/assets/images/govuk-opengraph-image.png
  component/package.json
  component/src/index.css
  component/src/index.css.map
  component/src/index.html
  component/src/index.js
  component/style.scss
  component/yarn.lock
Labels: component

#11 Bundle component code
  .gitignore
  README.md
  component/DELETE_tsconfig.json
  component/build.sh
  component/inject-inline-js.py
  component/package.json
  component/src/index.html
  component/src/index.js
  component/src/main.js
  component/webpack.config.js
  component/yarn.lock
Labels: component

#13 Initial function backend
  .gitignore
  backend/.python-version
  backend/backend_function/__init__.py
  backend/backend_function/function.json
  backend/host.json
  backend/requirements.txt
Labels: backend

#29 Add global variable to store scraped HTML
  component/src/main.js
Labels: component

#27 prettier component, better text, and nicer display on frontend
  component/dist/index.html
  component/dist/main.js
  component/src/index.html
  component/src/main.js
  demo/www.gov.uk/foreign-travel-advice/france/entry-requirements.html
Labels: component

#35 connect component to backend
  component/src/main.js
Labels: component

#37 Use nunjucks and add build step for demo
  demo/.gitignore
  demo/package.json
  demo/www.gov.uk/foreign-travel-advice/france/entry-requirements.html
  demo/yarn.lock
Labels: demo
